### ISSUE TITLE
[BUG] Recurrent ConcurrentModificationException

### ISSUE THREAD

**Issue by akashsriramganapathy** [DHD2280/BCR-Manager#4]
**Issue Description:**
Encountering a recurring `java.util.ConcurrentModificationException` error at irregular intervals in app version 1.2.0.

**To Reproduce:**
The bug occurs intermittently with no specific steps to reproduce. However, it consistently appears after the app has been open for a prolonged period with occasional long intervals.

**Expected Behavior:**
Describe the expected behavior when using the app for an extended period, including any relevant details.

**Logs:**
Include relevant log entries capturing the `java.util.ConcurrentModificationException` error. Provide timestamps and any additional context from the logs that may help diagnose the issue.

```java
java.util.ConcurrentModificationException
    at java.util.ArrayList.sort(ArrayList.java:1472)
    at it.dhd.bcrmanager.viewmodel.DataRepository.setupContactShortcuts(DataRepository.java:741)
    at it.dhd.bcrmanager.viewmodel.DataRepository.parseJson(DataRepository.java:621)
    at it.dhd.bcrmanager.viewmodel.DataRepository.lambda$fetchData$0(DataRepository.java:68)
    at it.dhd.bcrmanager.viewmodel.DataRepository.$r8$lambda$93UXNR-qGMBoj9N8nSSC4ESxOOM(Unknown Source:0)
    at it.dhd.bcrmanager.viewmodel.DataRepository$$ExternalSyntheticLambda6.call(Unknown Source:6)
    at io.reactivex.rxjava3.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:46)
    at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13262)
    at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
    at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
    at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
    at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
```

**Device Information:**
- Device: Xiaomi Mi 11X 5G
- OS: LineageOS 20 - Android 13
- App Version: 1.2.0

This information will assist developers in diagnosing and resolving the issue.

**Comment by DHD2280** [comment]
Let me know if with latest release [v1.2.2](https://github.com/DHD2280/BCR-Manager/releases/tag/v1.2.2) works.

**Comment by DHD2280** [comment]
Please try [this](https://1drv.ms/u/s!Am-ZBPpNlIhhiKFQaclmhaRi5aCDOg?e=rQiw0S)
