### ISSUE TITLE
[BUG] Crash on Delete.

### ISSUE THREAD

**Issue by nutzboi** [DHD2280/BCR-Manager#9]
**Describe the bug**
BCR Manager crashes when you attempt to delete a recording without playing any recording first.
**To Reproduce**
1. Launch BCR Manager.
2. Select a recording.
3. Choose Delete.
4. Confirm deletion.
5. Encounter error.

**Expected behavior**
Recording should get deleted.

**Screenshots**
![Screenshot_20241107-190713_BCR_Manager 1](https://github.com/user-attachments/assets/5aa06eaa-d632-42bd-ab97-b579ad5c1803)

**Device and Environment:**
 - Device: Xiaomi Redmi Note 10 Pro (sweet)
 - OS: crDroid 10.9 (Oct 13 build) - Android 14
 - Version 1.2.2
 - Recordings Path: ``/storage/emulated/0/Android/media/com.chiller3.bcr/files``

**Additional context**
If you play any recording when you launch the app, you can delete it and delete any other recording after that. If you try to delete a recording before playing any one first, it crashes with this error.

Log text (same as in screenshot):
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String it.dhd.bcrmanager.objects.CallLogItem.getFileName()' on a null object reference
	at it.dhd.bcrmanager.ui.fragments.Home.lambda$onDelete$24(Home.java:953)
	at it.dhd.bcrmanager.ui.fragments.Home.$r8$lambda$rXGKIgroi1AIGFLse1u6CgpDzrI(Unknown Source:0)
	at it.dhd.bcrmanager.ui.fragments.Home$$ExternalSyntheticLambda0.onItemDeleted(D8$$SyntheticClass:0)
	at it.dhd.bcrmanager.ui.dialogs.DeleteDialog.lambda$onCreateDialog$1(DeleteDialog.java:86)
	at it.dhd.bcrmanager.ui.dialogs.DeleteDialog.$r8$lambda$BM9IadCLP3hyyZAWN7DxJ4eQoyE(Unknown Source:0)
	at it.dhd.bcrmanager.ui.dialogs.DeleteDialog$$ExternalSyntheticLambda2.onClick(D8$$SyntheticClass:0)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
```

**Comment by DHD2280** [comment]
Hello
Can you try to use a different folder?
Set a new folder in bcr first, then set the folder in manager settings.
Thank you

**Comment by nutzboi** [comment]
Changed to `/storage/emulated/0/funny/`, still same issue.

**Comment by DHD2280** [comment]
Let me investigate

**Comment by nutzboi** [comment]
i deleted my fork to clean my profile up. anyways [this commit](https://github.com/DHD2280/BCR-Manager/pull/11/commits/6b0d6d37f108ddf76836daefa877e441f7869646) fixes it if you're still interested.
